### ISSUE TITLE
Improve interface for updating relations on Admin Panel.

### ISSUE THREAD

**Issue by WillNilges** [WillNilges/meshdb#112]
![Untitled](https://github.com/andybaumgar/meshdb/assets/42927786/a8cec1b5-1125-440a-80fa-b0d1e04fa0b1)

**Comment by Andrew-Dickinson** [comment]
This is most of the way there, but I think we still need some work on "reverse" relations. For example when adding an install to a building it's impossible to select a pre-existing install (instead you can only create a new one)

**Comment by Andrew-Dickinson** [comment]
Also, I don't think we want to encourage admins to add installs in that way, can we disable that option altogether?

**Comment by quoncc** [comment]
Not 100% sure what the issue is? This UI looks fine now

<img width="451" alt="image" src="https://github.com/WillNilges/meshdb/assets/76627323/ef0bc250-8bdc-427d-93f4-49bd7ef1a88b">

**Comment by Andrew-Dickinson** [comment]
Right, WIllard has done most of this, so the original issue text is a bit out of date. The remaining work is described by my comment above: 

> I think we still need some work on "reverse" relations. For example when adding an install to a building it's impossible to select a pre-existing install (instead you can only create a new one)
