### ISSUE TITLE
Create `Image` table

### ISSUE THREAD

**Issue by WillNilges** [WillNilges/meshdb#15]
We should omit this panoramaimage, and instead add a Photo object (maybe call it a pano or image or something)

Swift analog: https://github.com/andybaumgar/mesh-db-swift/blob/main/Sources/App/Models/Photo.swift

**Comment by Andrew-Dickinson** [comment]
We may be able to get away with referencing the Github repository for now: https://github.com/nycmeshnet/node-db/tree/master/data/panoramas

**Comment by Andrew-Dickinson** [comment]
Implemented in #216
