### ISSUE TITLE
Server error 500 when clicking Mesh API "Installs" from any other page

### ISSUE THREAD

**Issue by LydonThorpe** [WillNilges/meshdb#190]
http://db.grandsvc.mesh/admin/meshapi/install/ (accessed via SN1 Wireguard VPN) gives server error 500.
When clicked from either the /admin/ root page or from another (ex /meshapi/building/)

**Comment by Andrew-Dickinson** [comment]
Hm. I'm unable to reproduce it locally, @WillNilges maybe this is related to the force-push stuff tonight

**Comment by Andrew-Dickinson** [comment]
The box is set to SSH key only auth, and I don't have access, so Willard will have to look at this tomorrow

**Comment by Andrew-Dickinson** [comment]
Issue appears to be gone, closing for now

**Comment by Andrew-Dickinson** [comment]
Hm this is back again this afternoon...

**Comment by Andrew-Dickinson** [comment]
Root cause is likely out-of-date code on the import box. Running an off-cycle import with the latest code to check

**Comment by Andrew-Dickinson** [comment]
Yep confirmed. Closing
