### ISSUE TITLE
LOS tool broken due to mixed content requests

### ISSUE THREAD

**Issue by andybaumgar** [WillNilges/meshdb#270]
<img width="575" alt="image" src="https://github.com/WillNilges/meshdb/assets/711780/1e48f594-eb9a-4471-9123-2fa9cbcf8c00">

**Comment by Andrew-Dickinson** [comment]
Oh welp I guess I gotta do HTTPS on the backend side

**Comment by Andrew-Dickinson** [comment]
Should be fixed once @WillNilges deploys the new image. Thanks for forcing me to finally learn let's encrypt
