### ISSUE TITLE
Build admin panel

### ISSUE THREAD

**Issue by WillNilges** [WillNilges/meshdb#57]
https://stackoverflow.com/questions/47752994/purpose-of-admin-py-file-in-app-in-django-project

Might be able to do some fun and cool and useful things in here.

https://github.com/andybaumgar/meshdb/blob/90e51008b810cb1c305e8950396c85f0a7354263/src/meshapi/admin.py

**Comment by Andrew-Dickinson** [comment]
This is an old issue and is complete
