### ISSUE TITLE
Determine if code coverage is accurate when using abstractions like serializers etc.

### ISSUE THREAD

**Issue by andybaumgar** [WillNilges/meshdb#72]
In https://github.com/andybaumgar/meshdb/pull/70#issuecomment-1732398269 we get near 100% test coverage despite not testing many features of our app.  This might be fine since Django and Django Rest Framework libraries abstracts that from us, but I still have a gut instinct that we should test things a bit.  For example, in serializers.py we may want to codify the format that is produced by default.  Right now if the serializer behavior changes and outputs a different format no errors would be thrown despite 100% coverage.

**Comment by Andrew-Dickinson** [comment]
Our current testing approach of invoking the HTTP endpoint with the Django testing client and asserting things about the output JSON structure tests all relevant configuration and logical lines in the view, serializer, model, etc. There are some URLs with poor coverage (this is called out in #148) and the views for those URLs do show as "uncovered" in the current reports.

Overall our coverage is pretty good though. I don't think there's any work remaining here that's not captured in other tickets.
