### ISSUE TITLE
Add `notes` TextField and a `DIY` boolean to install model

### ISSUE THREAD

**Issue by WillNilges** [WillNilges/meshdb#73]

**Comment by Andrew-Dickinson** [comment]
The notes field is present. Are we still interested in the `DIY` bool?

**Comment by Andrew-Dickinson** [comment]
I don't believe we don't have this information currently, so maybe we'd have to assume that all installs are not DIY?

**Comment by Andrew-Dickinson** [comment]
Actually I guess looking for the text "DIY" in the notes field is a pretty good signal

**Comment by Andrew-Dickinson** [comment]
#161
